---
- when:
    - remmina.enable
  tags:
    - remmina
  block:
    - ansible.builtin.import_tasks:
        file: "install.yml"
      tags:
        - remmina-install
    - ansible.builtin.import_tasks:
        file: "configure.yml"
      tags:
        - remmina-configure
    - ansible.builtin.import_tasks:
        file: "{{ playbook_dir + '/includes/audit.yml' }}"
      tags:
        - remmina-audit
  rescue:
    - ansible.builtin.meta: flush_handlers
...
