---
- name: install | install package updates
  ansible.builtin.apt:
    state: present
    pkg:
      - bridge-utils
      - libvirt-clients
      - libvirt-daemon-system
      - qemu-kvm
      - virt-manager
      - p7zip-full

- name: install | add {{ user }} to kvm group
  ansible.builtin.user:
    name: "{{ user }}"
    groups: kvm
    append: true
  notify: reboot
...
