---
- name: install | install package updates
  ansible.builtin.apt:
    state: present
    pkg:
      - bridge-utils
      - libvirt-clients
      - libvirt-daemon-system
      - qemu-kvm
      - virt-manager
      - virtinst

- name: install | add {{ user }} to kvm group
  ansible.builtin.user:
    name: "{{ user }}"
    groups:
      - kvm
      - libvirt
    append: true
  notify: reboot

- name: configure | start & enable service
  ansible.builtin.systemd:
    name: libvirtd
    state: started
    enabled: true
...
