---
- name: install | validate task list parameters
  run_once: true
  assert:
    that:
      - protonmail_bridge.pubkey is defined
      - protonmail_bridge.policy is defined
      - protonmail_bridge.deb is defined
    quiet: true

- name: install | install dependencies
  apt:
    state: latest
    pkg:
      - debsig-verify
      - debian-keyring
      - ca-certificates
  notify:
    - apt-get clean

- name: install | install ProtonMail Bridge
  block:
    - name: configure | create necessary directories
      file:
        path: "{{ item + 'E2C75D68E6234B07' }}"
        state: directory
      loop:
        - /usr/share/debsig/keyrings/
        - /etc/debsig/policies/

    - name: install | download public key 
      get_url:
        url: "{{ 'https://' + protonmail_bridge.pubkey }}" 
        dest: /tmp
      register: pubkey 

    - name: install | import public key to keyring
      shell: >
        gpg
        --dearmor
        --output /usr/share/debsig/keyrings/E2C75D68E6234B07/debsig.gpg
        "{{ pubkey.dest }}"

    - name: install | download policy file 
      get_url:
        url: "{{ 'https://' + protonmail_bridge.policy }}" 
        dest: /etc/debsig/policies/E2C75D68E6234B07
      when:
        - not ansible_check_mode

    - name: install | download ProtonMail Bridge installer 
      get_url:
        url: "{{ 'https://' + protonmail_bridge.deb }}" 
        dest: /tmp
      register: deb 

    - name: install | verify ProtonMail Bridge installer integrity 
      shell: debsig-verify "{{ deb.dest }}"

    - name: install | install ProtonMail Bridge 
      apt:
        state: present
        deb: "{{ deb.dest }}" 
      when:
        - not ansible_check_mode
      notify:
        - apt-get clean

    - name: install | remove artifacts 
      file:
        path: "{{ item }}"
        state: absent
      loop:
        - "{{ pubkey.dest }}"
        - "{{ deb.dest }}"
  when:
    - '"protonmail-bridge" not in ansible_facts.packages'

- name: install | import GPG key binary to keyring
  copy:
    src: ~/.config/protonmail/bridge/cert.pem
    dest:  /usr/local/share/ca-certificates/protonbridge.crt
    owner: root
    group: root
    mode: 0644
  notify:
    - update-ca-certificates
