---
- name: configure | Create necessary directories
  file:
    path: "{{ ansible_facts.user_dir + '/' + ncmpcpp.config_dir }}"
    state: directory

- name: configure | deploy config file
  copy:
    src: bindings
    dest: "{{ ansible_facts.user_dir + '/' + ncmpcpp.config_dir }}"

- name: configure | deploy config file
  template:
    src: config.j2
    dest: "{{ [ansible_facts.user_dir,ncmpcpp.config_dir,'config'] | join('/') }}"
...
