---
- when:
    - ncmpcpp.enable
  tags:
    - ncmpcpp
  block:
    - ansible.builtin.import_tasks:
        file: "install.yml"
      tags:
        - ncmpcpp-install
    - ansible.builtin.import_tasks:
        file: "configure.yml"
      tags:
        - ncmpcpp-configure
    - ansible.builtin.import_tasks:
        file: "{{ playbook_dir + '/includes/audit.yml' }}"
      tags:
        - ncmpcpp-audit
  rescue:
    - ansible.builtin.meta: flush_handlers
...
