---
- block:
    - import_tasks: "install.yml"
      tags:
        - ncmpcpp-install
    - import_tasks: "configure.yml"
      tags:
        - ncmpcpp-configure
    - import_tasks: "validate.yml"
      tags:
        - ncmpcpp-validate
  rescue:
    - meta: flush_handlers
  tags:
    - ncmpcpp
...
