---
- when:
    - ncmpcpp.enable
  tags:
    - ncmpcpp
  block:
    - ansible.builtin.import_tasks: "install.yml"
      tags:
        - ncmpcpp-install
    - ansible.builtin.import_tasks: "configure.yml"
      tags:
        - ncmpcpp-configure
    - ansible.builtin.import_tasks: "validate.yml"
      tags:
        - ncmpcpp-validate
  rescue:
    - ansible.builtin.meta: flush_handlers
...
