---
- name: install | validate task list parameters
  run_once: true
  assert:
    that:
      - signal_desktop.repo.key
      - signal_desktop.repo.keyring
      - signal_desktop.repo.url
      - signal_desktop.repo.arch
      - signal_desktop.repo.release
    quiet: true

- name: install | check if repository keyring exists
  stat:
    path: "{{ signal_desktop.repo.keyring }}"
  register: repo_keyring

- name: install | import repository key
  block:
    - name: install | download ASCII-armored OpenPGP repository key
      get_url:
        url: "{{ 'https://' + signal_desktop.repo.key }}"
        dest: /tmp
      register: repo_key

    - name: install | unpack ASCII-armored OpenPGP repository key
      shell: cat "{{ repo_key.dest }}" | gpg --dearmor
      register: output

    - name: install | import GPG key binary to keyring
      copy:
        content: "{{ output.stdout }}"
        dest: "{{ signal_desktop.repo.keyring }}"

    - name: install | remove artifacts
      file:
        path: "{{ repo_key.dest }}"
        state: absent
  when:
    - not repo_keyring.stat.exists

- name: install | add repository to APT source list
  apt_repository:
    repo: >
      deb
      [arch={{ signal_desktop.repo.arch }} signed-by={{ signal_desktop.repo.keyring }}]
      {{ signal_desktop.repo.url }}
      {{ signal_desktop.repo.release }}
      main
    state: present
    filename: "{{ 'signal' + signal_desktop.repo.release }}"

- name: install | install package updates
  apt:
    state: latest
    pkg:
      - signal-desktop
