---
- name: configure | set default web browser
  alternatives:
    name: x-www-browser
    link: /usr/bin/x-www-browser
    path: /usr/bin/qutebrowser
    priority: 50

- name: configure | create necessary directories
  file:
    path: "{{ ansible_facts.user_dir + '/' + qutebrowser.config_dir }}"
    state: directory
    owner: "{{ user }}"
    group: "{{ user }}"

- name: configure | deploy config file
  copy:
    src: "{{ item }}"
    dest: "{{ ansible_facts.user_dir + '/' + qutebrowser.config_dir }}"
    owner: "{{ user }}"
    group: "{{ user }}"
  loop:
    - config.py
    - nord-qutebrowser.py
...
