---
- name: install | install package updates
  ansible.builtin.apt:
    state: latest
    pkg:
      - qutebrowser

- name: install | update fonts
  ansible.builtin.apt:
    state: latest
    pkg:
      - fonts-jetbrains-mono
  notify:
    - fc-cache
...
