---
- when:
    - qutebrowser.enable
  tags:
    - qutebrowser
  block:
    - ansible.builtin.import_tasks: "install.yml"
      tags:
        - qutebrowser-install
    - ansible.builtin.import_tasks: "configure.yml"
      tags:
        - qutebrowser-configure
    - ansible.builtin.import_tasks: "validate.yml"
      tags:
        - qutebrowser-validate
  rescue:
    - ansible.builtin.meta: flush_handlers
...
