---
- when:
    - qutebrowser.enable
  tags:
    - qutebrowser
  block:
    - ansible.builtin.import_tasks:
        file: "install.yml"
      tags:
        - qutebrowser-install
    - ansible.builtin.import_tasks:
        file: "configure.yml"
      tags:
        - qutebrowser-configure
    - ansible.builtin.import_tasks:
        file: "{{ playbook_dir + '/includes/audit.yml' }}"
      tags:
        - qutebrowser-audit
  rescue:
    - ansible.builtin.meta: flush_handlers
...
