---
- block:
    - import_tasks: "install.yml"
      tags:
        - qutebrowser-install
    - import_tasks: "configure.yml"
      tags:
        - qutebrowser-configure
    - import_tasks: "validate.yml"
      tags:
        - qutebrowser-validate
  rescue:
    - meta: flush_handlers
  tags:
    - qutebrowser
...
