---
- name: install | install package updates
  ansible.builtin.apt:
    state: latest
    pkg:
      - cool-retro-term

- name: install | install font updates
  ansible.builtin.apt:
    pkg:
      - fonts-jetbrains-mono
    state: latest
  notify:
    - fc-cache.
...
