---
- when:
    - crt.enable
  tags:
    - crt
  block:
    - ansible.builtin.import_tasks: "install.yml"
      tags:
        - crt-install
    - ansible.builtin.import_tasks: "configure.yml"
      tags:
        - crt-configure
    - ansible.builtin.import_tasks: "{{ playbook_dir + '/includes/audit.yml' }}"
      tags:
        - crt-audit
  rescue:
    - ansible.builtin.meta: flush_handlers
...
