name = "Chris Powell"
downloads-dir = "/home/chris/Downloads"
signature = """
Cordialement,
Regards,
"""

[protonmail]
default = true
email = "chris.m.powell@protonmail.com"

imap-host = "127.0.0.1"
imap-port = 1143
imap-login = "chris.m.powell@protonmail.com"
imap-passwd-cmd = "pass show protonmail/imap"
imap-starttls = true

smtp-host = "127.0.0.1"
smtp-port = 1025
smtp-login = "chris.m.powell@protonmail.com"
smtp-passwd-cmd = "pass show protonmail/smtp"
smtp-starttls = true
