---
- when:
    - cosmic.enable
  tags:
    - cosmic
  block:
    - ansible.builtin.import_tasks: "shell.yml"
      tags:
        - cosmic-shell
    - ansible.builtin.import_tasks: "shell_shortcuts.yml"
      tags:
        - cosmic-shortcuts
    - ansible.builtin.import_tasks: "workspaces.yml"
      tags:
        - cosmic-workspaces
    - ansible.builtin.import_tasks: "{{ playbook_dir + '/includes/audit.yml' }}"
      tags:
        - cosmic-audit
  rescue:
    - ansible.builtin.meta: flush_handlers
...
