---
- name: install | check if shell extension is installed
  become_user: "{{ user }}"
  ansible.builtin.stat:
    path: /usr/local/bin/pop-shell-shortcuts
  register: shell_shortcuts_extension

- name: install | build extensions from source
  when:
    - not shell_shortcuts_extension.stat.exists
  block:
    - name: install | install build dependencies
      ansible.builtin.apt:
        state: latest
        pkg:
          - cargo
          - rustc
          - libgtk-3-dev

    - name: install | clone extensions
      become_user: "{{ user }}"
      ansible.builtin.git:
        repo: "{{ 'https://' + cosmic.extensions.shell_shortcuts.repo }}"
        dest: "{{ '/tmp/' + cosmic.extensions.shell_shortcuts.dest }}"
        force: true
        depth: 1
        single_branch: true

    - name: install | build shell shortcuts extension
      become_user: "{{ user }}"
      ansible.builtin.command: make
      args:
        chdir: "{{ '/tmp/' + cosmic.extensions.shell_shortcuts.dest }}"
      changed_when: true

    - name: install | build shell shortcuts extension
      ansible.builtin.command: make install
      args:
        chdir: "{{ '/tmp/' + cosmic.extensions.shell_shortcuts.dest }}"
      changed_when: true

    - name: install | remove build artifacts
      ansible.builtin.file:
        path: "{{ '/tmp/' + cosmic.extensions.shell_shortcuts.dest }}"
        state: absent
...
