---
- name: install | check if shell extension is installed
  ansible.builtin.stat:
    path: "{{ ansible_facts.user_dir + '/.local/share/gnome-shell/extensions/pop-shell@system76.com' }}"
  register: shell_extension

- name: install | build extensions from source
  when:
    - not shell_extension.stat.exists
  block:
    - name: install | install build dependencies
      ansible.builtin.apt:
        state: present
        pkg:
          - node-typescript
          - make
          - git

    - name: install | clone extensions
      become_user: "{{ user }}"
      ansible.builtin.git:
        repo: "{{ 'https://' + cosmic.extensions.shell.repo }}"
        dest: "{{ '/tmp/' + cosmic.extensions.shell.dest }}"
        force: true
        depth: 1

    - name: install | build shell extension
      become_user: "{{ user }}"
      community.general.make:
        chdir: "{{ '/tmp/' + cosmic.extensions.shell.dest }}"
        target: local-install

    - name: install | remove build artifacts
      ansible.builtin.file:
        path: "{{ '/tmp/' + cosmic.extensions.shell.dest }}"
        state: absent
...
