---
- name: install | check if workspaces extension is installed
  become_user: "{{ user }}"
  ansible.builtin.stat:
    path: ~/.local/share/gnome-shell/extensions/cosmic-workspaces@system76.com
  register: workspaces_extension

- name: install | build extensions from source
  become_user: "{{ user }}"
  when:
    - not workspaces_extension.stat.exists
  block:
    - name: install | clone workspaces extension
      ansible.builtin.git:
        repo: "{{ 'https://' + cosmic.extensions.workspaces.repo }}"
        dest: "{{ '/tmp/' + cosmic.extensions.workspaces.dest }}"
        force: true
        depth: 1
        single_branch: true

    - name: install | make workspaces extension
      community.general.make:
        chdir: "{{ '/tmp/' + cosmic.extensions.workspaces.dest }}"

    - name: install | install workspaces extension
      community.general.make:
        chdir: "{{ '/tmp/' + cosmic.extensions.workspaces.dest }}"
        target: install

    - name: install | install workspaces extension
      ansible.builtin.command: gnome-extensions enable cosmic-workspaces@system76.com
      changed_when: true

    - name: install | remove build artifacts
      ansible.builtin.file:
        path: "{{ '/tmp/' + cosmic.extensions.workspaces.dest }}"
        state: absent
...
