---
- name: install | validate task list parameters
  run_once: true
  assert:
    that:
      bitwarden_cli.pkg is defined
    quiet: true

- name: install | extract remote archive
  unarchive:
    src: "{{ 'https://' + bitwarden_cli.pkg }}"
    dest: /usr/local/bin
    include: bw
    remote_src: true
    list_files: true
    mode: +x

- name: install | install package updates
  apt:
    state: latest
    pkg:
      - jq
  notify:
    - apt-get clean
