---
- name: kernel | enforce kernel paramaters
  ansible.posix.sysctl:
    name: "{{ item.key }}"
    value: "{{ item.value }}"
    state: present
    sysctl_set: true
    sysctl_file: /etc/sysctl.d/99-hardening-ansible.conf
    reload: true
  loop: "{{ hardening.sysctl | dict2items }}"
...
