---
- when:
    - hardening.enable
  tags:
    - hardening
  block:
    - ansible.builtin.import_tasks:
        file: "kernel.yml"
      tags:
        - hardening-kernel
    - ansible.builtin.import_tasks:
        file: "fs.yml"
      tags:
        - hardening-fs
    - ansible.builtin.import_tasks:
        file: "systemd.yml"
      tags:
        - hardening-systemd
    - ansible.builtin.import_tasks:
        file: "ufw.yml"
      tags:
        - hardening-ufw
    - ansible.builtin.import_tasks:
        file: "ssh.yml"
      tags:
        - hardening-ssh
    - ansible.builtin.import_tasks:
        file: "misc.yml"
      tags:
        - hardening-misc
  rescue:
    - ansible.builtin.meta: flush_handlers
...
