---
- name: misc | install rootkit detection
  ansible.builtin.apt:
    state: latest
    pkg: rkhunter

- name: misc | install auditing tools
  ansible.builtin.apt:
    state: latest
    pkg: lynis

- name: misc | remove unnecessary packages
  ansible.builtin.apt:
    state: absent
    purge: true
    pkg: "{{ hardening.misc.unnecessary_pkgs }}"
...
