---
- name: configure | create necessary directories
  ansible.builtin.file:
    path: "{{ ansible_facts.user_dir + '/' + protonvpn.config_dir }}"
    state: directory
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: 0750

- name: configure | deploy config file
  ansible.builtin.copy:
    src: user_configurations.json
    dest: "{{ ansible_facts.user_dir + '/' + protonvpn.config_dir }}"
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: 0640
...
