---
- name: install | validate task list parameters
  run_once: true
  assert:
    that:
      - protonvpn.pkg is defined
    quiet: true

- name: install | setup repository 
  block: 
    - name: install | download ProtonVPN stable release repository installer 
      get_url:
        url: "{{ 'https://' + protonvpn.pkg }}" 
        dest: /tmp 
        validate_certs: true
      register: pkg 

    - name: install | setup ProtonVPN stable release repository
      apt:
        state: present
        deb: "{{ pkg.dest }}" 
      when:
        - not ansible_check_mode
      notify:
        - apt-get clean

    - name: install | remove artifacts
      file:
        path: "{{ pkg.dest }}" 
        state: absent
      when:
        - not ansible_check_mode
  when:
    - '"protonvpn-stable-release" not in ansible_facts.packages'

- name: install | install or update ProtonVPN CLI
  apt:
    update_cache: true
    state: latest
    pkg:
      - protonvpn-cli
  notify:
    - apt-get clean
