---
- block:
    - import_tasks: "install.yml"
      tags:
        - protonvpn-install
    - import_tasks: "configure.yml"
      tags:
        - protonvpn-configure
  rescue:
    - meta: flush_handlers
  tags:
    - protonvpn
