---
- when:
    - protonvpn.enable
  tags:
    - protonvpn
  block:
    - ansible.builtin.import_tasks: "install.yml"
      tags:
        - protonvpn-install
    - ansible.builtin.import_tasks: "configure.yml"
      tags:
        - protonvpn-configure
  rescue:
    - ansible.builtin.meta: flush_handlers
...
