---
- name: Verify existence of resident user account {{ user }}
  ansible.builtin.getent:
    database: passwd
    key: "{{ user }}"

- name: Gather service facts
  ansible.builtin.service_facts:

- name: Gather package facts
  ansible.builtin.package_facts:
    manager: auto

- name: Gather listening ports facts
  community.general.system.listen_ports_facts:

- name: Get user home directory
  become_user: "{{ user }}"
  ansible.builtin.setup:
    gather_subset: user_dir
...
