---
- name: configure | create necessary directories
  file:
    path: "{{ ansible_facts.user_dir + '/' + ranger.config_dir }}"
    state: directory
    owner: "{{ user }}"
    group: "{{ user }}"

- name: configure | deploy config file
  copy:
    src: rc.conf
    dest: "{{ ansible_facts.user_dir + '/' + ranger.config_dir }}"
    owner: "{{ user }}"
    group: "{{ user }}"
...
