---
- name: install | install package updates
  ansible.builtin.apt:
    state: present
    pkg:
      - ranger
      - caca-utils
      - highlight
      - atool
      - w3m
      - poppler-utils
      - mediainfo
...
