---
- name: install | install package updates
  apt:
    state: latest
    pkg:
      - ranger
      - caca-utils
      - highlight
      - atool
      - w3m
      - poppler-utils
      - mediainfo
...
