---
- when:
    - ranger.enable
  tags:
    - ranger
  block:
    - ansible.builtin.import_tasks:
        file: "install.yml"
      tags:
        - ranger-install
    - ansible.builtin.import_tasks:
        file: "configure.yml"
      tags:
        - ranger-configure
    - ansible.builtin.import_tasks:
        file: "{{ playbook_dir + '/includes/audit.yml' }}"
      tags:
        - ranger-audit
  rescue:
    - ansible.builtin.meta: flush_handlers
...
