---
- name: ssh | validate task list parameters
  run_once: true
  assert:
    that:
      - ssh.sshd_config | length > 0
    quiet: true

- name: install | set sshd_config parameters
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '(?i)^#*?\s*{{ item.key | regex_escape() }}\s+'
    line: "{{ item.key }} {{ item.value }}"
    owner: root
    group: root
    mode: 0644
    validate: /usr/sbin/sshd -tf %s
  when:
    - '"ssh" in ansible_facts.packages or ssh_pkg.changed'
    - item.value
  loop: "{{ ssh.sshd_config | dict2items }}"
  notify: restart ssh

- name: install | set TCP wrappers
  lineinfile:
    path: "{{ item.path }}"
    regexp: '^#*?\s*sshd:\s*{{ item.line | regex_escape() }}\s*'
    line: "{{ 'sshd: ' + item.line }}"
    owner: root
    group: root
    mode: 0644
  when:
    - '"ssh" in ansible_facts.packages or ssh_pkg.changed'
  loop:
    - { path: '/etc/hosts.allow', line: '192.168.0.0/24'}
    - { path: '/etc/hosts.allow', line: '127.0.0.1' }
    - { path: '/etc/hosts.deny', line: 'ALL' }


# - name: ssh | copy banner text
#   copy:
#     content: "{{ hardening.banner.text }}"
#     dest: "{{ hardening.sshd.Banner }}"
#     owner: root
#     group: root
#     mode: 0644
#   when:
#     - hardening.ssh.Banner
#     - ansible_facts.services['ssh']['state'] == "running"
