---
- name: configure | deploy config file
  ansible.builtin.copy:
    src: .zshrc
    dest: "{{ ansible_facts.user_dir }}"
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: 0640

- name: configure | set default shell
  ansible.builtin.command: usermod --shell /usr/bin/zsh "{{ user }}"
  changed_when: false
...
