---
- when:
    - zsh.enable
  tags:
    - zsh
  block:
    - ansible.builtin.import_tasks:
        file: "install.yml"
      tags:
        - zsh-install
    - ansible.builtin.import_tasks:
        file: "configure.yml"
      tags:
        - zsh-configure
    - ansible.builtin.import_tasks:
        file: "{{ playbook_dir + '/includes/audit.yml' }}"
      tags:
        - zsh-audit
  rescue:
    - ansible.builtin.meta: flush_handlers
...
