---
- name: install | create necessary directories
  ansible.builtin.file:
    path: "{{ ansible_facts.user_dir + '/.themes' }}"
    state: directory
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: 0750

- name: install | clone project repository
  ansible.builtin.git:
    repo: "{{ 'https://' + item.repo }}"
    dest: "{{ ansible_facts.user_dir + '/' + item.dest }}"
    depth: 1
    single_branch: true
  loop: "{{ gtk.theme }}"
...
