---
- name: install | create necessary directories
  file:
    path: "{{ ansible_facts.user_dir + '/.themes' }}"
    state: directory

- name: install | clone project repository
  git:
    repo: "{{ 'https://' + item.repo }}"
    dest: "{{ ansible_facts.user_dir + '/' + item.dest }}"
    depth: 1
    single_branch: true
  loop: "{{ gtk.theme }}"
...
