---
- when:
    - gtk.enable
  tags:
    - gtk
  block:
    - ansible.builtin.import_tasks:
        file: "install.yml"
      tags:
        - gtk-install
    - ansible.builtin.import_tasks:
        file: "configure.yml"
      tags:
        - gtk-configure
    - ansible.builtin.import_tasks:
        file: "{{ playbook_dir + '/includes/audit.yml' }}"
      tags:
        - gtk-audit
  rescue:
    - ansible.builtin.meta: flush_handlers
...
