---
- block:
    - import_tasks: "install.yml"
      tags:
        - gtk-install
    - import_tasks: "configure.yml"
      tags:
        - gtk-configure
    - import_tasks: "validate.yml"
      tags:
        - gtk-validate
  rescue:
    - meta: flush_handlers
  tags:
    - gtk
...
