---
- block:
    - import_tasks: "install.yml"
      tags:
        - gtk-install
    - import_tasks: "configure.yml"
      tags:
        - gtk-configure
  rescue:
    - meta: flush_handlers
  tags:
    - gtk
...
