---
- name: install | clone project repository
  become_user: "{{ user }}"
  git:
    repo: "{{ 'https://' + dircolors.theme.nord.repo }}"
    dest: "{{ dircolors.theme.nord.dest }}"
    force: true
    depth: 1
    single_branch: true
  changed_when: false

- name: install | enable
  block:
    - name: install | copy source file to user home directory
      become_user: "{{ user }}"
      copy:
        src: "{{ dircolors.theme.nord.dest + '/src/dir_colors' }}"
        dest: ~/.dir_colors
        remote_src: true

    - name: install | remove install artifacts
      file:
        path: "{{ dircolors.theme.nord.dest }}"
        state: absent
      changed_when: false

    - name: install | activate
      become_user: "{{ user }}"
      lineinfile:
        path: ~/.bashrc
        state: present
        line: test -r ~/.dir_colors && eval $(dircolors ~/.dir_colors)
        insertafter: EOF
      loop:
        - ~/.bashrc
        - ~/.zshrc
  when:
    - not ansible_check_mode
...
