---
- when:
    - dircolors.enable
  tags:
    - dircolors
  block:
    - ansible.builtin.import_tasks:
        file: "install.yml"
      tags:
        - dircolors-install
    - ansible.builtin.import_tasks:
        file: "{{ playbook_dir + '/includes/audit.yml' }}"
      tags:
        - dircolors-audit
  rescue:
    - ansible.builtin.meta: flush_handlers
...
