---
- name: fc-cache
  ansible.builtin.command: fc-cache -f
  listen: fc-cache

- name: update desktop database
  ansible.builtin.command: update-desktop-database
  listen: update-desktop-database

- name: reboot
  ansible.builtin.command: shutdown -r -t 30
  listen: reboot

- name: update-ca-certificates
  ansible.builtin.command: update-ca-certificates
  listen: update-ca-certificates

- name: restart ssh
  ansible.builtin.systemd:
    name: ssh
    enabled: true
    state: restarted
  listen: restart ssh

- name: reload systemd
  ansible.builtin.systemd:
    daemon_reload: true
...
