---
- name: configure | gitconfig
  become_user: "{{ user }}"
  community.general.source_control.git_config:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    scope: global
  loop: "{{ git.gitconfig }}"
...
