---
- name: configure | validate task list parameters
  run_once: true
  assert:
    that:
    quiet: true

- name: configure | gitconfig
  become_user: "{{ user }}"
  git_config:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    scope: file
    file: ~/.gitconfig
  loop: "{{ git.gitconfig }}"
...
