---
- when:
    - git.enable
  tags:
    - git
  block:
    - ansible.builtin.import_tasks:
        file: "install.yml"
      tags:
        - git-install
    - ansible.builtin.import_tasks:
        file: "configure.yml"
      tags:
        - git-configure
    - ansible.builtin.import_tasks:
        file: "{{ playbook_dir + '/includes/audit.yml' }}"
      tags:
        - git-audit
  rescue:
    - ansible.builtin.meta: flush_handlers
...
