---
- when:
    - git.enable
  tags:
    - git
  block:
    - ansible.builtin.import_tasks: "install.yml"
      tags:
        - git-install
    - ansible.builtin.import_tasks: "configure.yml"
      tags:
        - git-configure
  rescue:
    - ansible.builtin.meta: flush_handlers
...
