---
- block:
    - import_tasks: "install.yml"
      tags:
        - git-install
    - import_tasks: "configure.yml"
      tags:
        - git-configure
  rescue:
    - meta: flush_handlers
  tags:
    - git
