---
- name: configure | deploy configurations
  become_user: "{{ user }}"
  block:
    - name: configure | create necessary directories
      file:
        path: "{{ protonvpn_cli.config.dir }}"
        state: directory

    - name: configure | deploy config file
      copy:
        src: user_configurations.json
        dest: "{{ protonvpn_cli.config.dir }}"
...
