---
- name: install | setup repository
  block:
    - name: install | download Proton VPN stable release repository installer
      get_url:
        url: "{{ 'https://' + protonvpn_cli.pkg }}"
        dest: /tmp
        validate_certs: true
      register: pkg

    - name: install | setup Proton VPN stable release repository
      apt:
        state: present
        deb: "{{ pkg.dest }}"
      when:
        - not ansible_check_mode

    - name: install | remove artifacts
      file:
        path: "{{ pkg.dest }}"
        state: absent
      when:
        - not ansible_check_mode
  when:
    - '"protonvpn-stable-release" not in ansible_facts.packages'

- name: install | install or update Proton VPN CLI
  apt:
    update_cache: true
    state: latest
    pkg:
      - protonvpn-cli
...
