---
- name: install | extract remote archive
  ansible.builtin.unarchive:
    src: "{{ 'https://' + bitwarden_cli.pkg }}"
    dest: /usr/local/bin
    owner: root
    group: root
    mode: 0755
    remote_src: true
    list_files: true

- name: install | install package updates
  ansible.builtin.apt:
    state: present
    pkg:
      - jq
...
