---
- name: install | report host virtualization status
  ansible.builtin.debug:
    msg: This system is virtual, skipping VirtualBox installation...
  when:
    - ansible_virtualization_role == "guest"

- name: install | initiate install procedure
  when:
    - ansible_virtualization_role != "guest"
  block:
    - name: install | check if repository keyring exists
      ansible.builtin.stat:
        path: "{{ virtualbox.repo.keyring }}"
      register: repo_keyring

    - name: install | import repository key
      when:
        - not repo_keyring.stat.exists
      block:
        - name: install | download ASCII-armored OpenPGP repository key
          ansible.builtin.get_url:
            url: "{{ 'https://' + virtualbox.repo.key }}"
            dest: /tmp
            owner: root
            group: root
            mode: 0644
          register: repo_key

        - name: install | unpack ASCII-armored OpenPGP repository key
          ansible.builtin.shell: cat "{{ repo_key.dest }}" | gpg --dearmor
          changed_when: false
          register: output

        - name: install | import GPG key binary to keyring
          ansible.builtin.copy:
            content: "{{ output.stdout }}"
            dest: "{{ virtualbox.repo.keyring }}"
            owner: root
            group: root
            mode: 0644

        - name: install | remove artifacts
          ansible.builtin.file:
            path: "{{ repo_key.dest }}"
            state: absent

    - name: install | add repository to APT source list
      ansible.builtin.apt_repository:
        repo: >
          deb
          [arch={{ virtualbox.repo.arch }} signed-by={{ virtualbox.repo.keyring }}]
          {{ virtualbox.repo.url }}
          {{ virtualbox.repo.debian_release }}
          contrib
        state: present
        filename: virtualbox

    - name: install | install package updates
      ansible.builtin.apt:
        state: latest
        pkg:
          - dkms
          - virtualbox
      notify:
        - virtualbox-ext-pack
...
