---
- name: install | install package updates
  ansible.builtin.apt:
    state: present
    pkg:
      - virtualbox
      - p7zip-full

- name: install | accept PUEL for virtual-ext-pack installation
  ansible.builtin.shell: >
    echo virtualbox-ext-pack virtualbox-ext-pack/license select true | sudo debconf-set-selections
  changed_when: false

- name: install | install virtual-ext-pack
  ansible.builtin.apt:
    state: present
    pkg:
      - virtualbox-ext-pack
...
