---
- name: configure | create necessary directories
  file:
    path: "{{ ansible_facts.user_dir + '/' + zathura.config_dir }}"
    state: directory
    owner: "{{ user }}"
    group: "{{ user }}"

- name: configure | deploy config file
  copy:
    src: zathurarc
    dest: "{{ ansible_facts.user_dir + '/' + zathura.config_dir }}"
    owner: "{{ user }}"
    group: "{{ user }}"

- name: configure | check default PDF viewer
  become_user: "{{ user }}"
  command: xdg-mime query default application/pdf
  changed_when: false
  register: default_pdf_viewer

- name: configure | set default PDF viewer
  become_user: "{{ user }}"
  command: xdg-mime default org.pwmt.zathura.desktop application/pdf
  when:
    - default_pdf_viewer.stdout != "org.pwmt.zathura.desktop"
...
