---
- name: install | install package updates
  ansible.builtin.apt:
    state: latest
    pkg:
      - zathura
      - zathura-pdf-poppler
      - zathura-ps
      - zathura-cb
      - zathura-djvu
...
