---
- when:
    - zathura.enable
  tags:
    - zathura
  block:
    - ansible.builtin.import_tasks:
        file: "install.yml"
      tags:
        - zathura-install
    - ansible.builtin.import_tasks:
        file: "configure.yml"
      tags:
        - zathura-configure
    - ansible.builtin.import_tasks:
        file: "{{ playbook_dir + '/includes/audit.yml' }}"
      tags:
        - zathura-audit
  rescue:
    - ansible.builtin.meta: flush_handlers
...
