---
- when:
    - zathura.enable
  tags:
    - zathura
  block:
    - ansible.builtin.import_tasks: "install.yml"
      tags:
        - zathura-install
    - ansible.builtin.import_tasks: "configure.yml"
      tags:
        - zathura-configure
    - ansible.builtin.import_tasks: "validate.yml"
      tags:
        - zathura-configure
  rescue:
    - ansible.builtin.meta: flush_handlers
...
