---
- name: configure | create necessary directories
  file:
    dest: "{{ ansible_facts.user_dir + '/' + bpytop.config_dir }}"
    state: directory
    owner: "{{ user }}"
    group: "{{ user }}"

- name: configure | deploy config file
  copy:
    src: bpytop.conf
    dest: "{{ ansible_facts.user_dir + '/' + bpytop.config_dir }}"
    owner: "{{ user }}"
    group: "{{ user }}"
...
