---
- when:
    - bpytop.enable
  tags:
    - bpytop
  block:
    - ansible.builtin.import_tasks:
        file: "install.yml"
      tags:
        - bpytop-install
    - ansible.builtin.import_tasks:
        file: "configure.yml"
      tags:
        - bpytop-configure
    - ansible.builtin.import_tasks:
        file: "{{ playbook_dir + '/includes/audit.yml' }}"
      tags:
        - bpytop-audit
  rescue:
    - ansible.builtin.meta: flush_handlers
...
