---
- block:
    - import_tasks: "install.yml"
      tags:
        - bpytop-install
    - import_tasks: "configure.yml"
      tags:
        - bpytop-configure
    - import_tasks: "validate.yml"
      tags:
        - bpytop-validate
  rescue:
    - meta: flush_handlers
  tags:
    - bpytop
...
