---
- when:
    - bpytop.enable
  tags:
    - bpytop
  block:
    - ansible.builtin.import_tasks: "install.yml"
      tags:
        - bpytop-install
    - ansible.builtin.import_tasks: "configure.yml"
      tags:
        - bpytop-configure
    - ansible.builtin.import_tasks: "validate.yml"
      tags:
        - bpytop-validate
  rescue:
    - ansible.builtin.meta: flush_handlers
...
