---
- name: configure | validate task list parameters
  run_once: true
  assert:
    that:
      - himalaya.config.dir is defined
    quiet: true

- name: configure | deploy configurations
  become_user: "{{ user }}"
  block:
    - name: configure | create necessary directories
      file:
        path: "{{ himalaya.config.dir }}"
        state: directory

    - name: configure | deploy config file
      copy:
        src: config.toml
        dest: "{{ himalaya.config.dir }}"
