---
- name: install | install OpenSSL dependencies
  when:
    - '"libssl1.1" not in ansible_facts.packages'
  block:
    - name: install | download libssl and libcrypt libraries
      ansible.builtin.get_url:
        url: "{{ 'http://' + himalaya.libssl }}"
        dest: /tmp
        owner: root
        group: root
        mode: 0750
      register: libssl

    - name: install | instal libssl and libcrypt libraries
      ansible.builtin.apt:
        state: present
        deb: "{{ libssl.dest }}"
      when:
        - not ansible_check_mode

    - name: install | remove artifacts
      ansible.builtin.file:
        path: "{{ libssl.dest }}"
        state: absent

- name: install |  install pass
  ansible.builtin.apt:
    state: latest
    pkg:
      - pass

- name: install | extract binary from remote archive
  ansible.builtin.unarchive:
    src: "{{ 'https://' + himalaya.installer }}"
    dest: "{{ ansible_facts.user_dir + '/.local/bin' }}"
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: 0750
    remote_src: true
    list_files: true
    include:
      - himalaya
...
