---
- when:
    - himalaya.enable
  tags:
    - himalaya
  block:
    - ansible.builtin.import_tasks: "install.yml"
      tags:
        - himalaya-install
    - ansible.builtin.import_tasks: "configure.yml"
      tags:
        - himalaya-configure
  rescue:
    - ansible.builtin.meta: flush_handlers
