---
- block:
    - import_tasks: "install.yml"
      tags:
        - himalaya-install
    - import_tasks: "configure.yml"
      tags:
        - himalaya-configure
  rescue:
    - meta: flush_handlers
  tags:
    - himalaya
