---
- when:
    - himalaya.enable
  tags:
    - himalaya
  block:
    - ansible.builtin.import_tasks:
        file: "install.yml"
      tags:
        - himalaya-install
    - ansible.builtin.import_tasks:
        file: "configure.yml"
      tags:
        - himalaya-configure
    - ansible.builtin.import_tasks:
        file: "{{ playbook_dir + '/includes/audit.yml' }}"
      tags:
        - himalaya-audit
  rescue:
    - ansible.builtin.meta: flush_handlers
