---
- name: configure | create necessary directories
  file:
    path: "{{ ansible_facts.user_dir + '/' + item }}"
    state: directory
    owner: "{{ user }}"
    group: "{{ user }}"
    force: true
  loop:
    - "{{ mpd.config_dir }}"
    - "{{ mpd.playlist_dir }}"

- name: configure | create necessary files
  file:
    path: "{{ ansible_facts.user_dir + '/' + item }}"
    state: touch
    owner: "{{ user }}"
    group: "{{ user }}"
  changed_when: false
  loop:
    - "{{ mpd.db_file }}"
    - "{{ mpd.log_file }}"
    - "{{ mpd.pid_file }}"
    - "{{ mpd.state_file }}"

- name: configure | render config from template
  template:
    src: "mpd.conf.j2"
    dest: "{{ [ansible_facts.user_dir,mpd.config_dir,'mpd.conf'] | join('/') }}"
    owner: "{{ user }}"
    group: "{{ user }}"

- name: configure | start & enable service with user scope
  become_user: "{{ user }}"
  systemd:
    name: mpd
    state: started
    enabled: true
    scope: user
