---
- when:
    - mpd.enable
  tags:
    - mpd
  block:
    - ansible.builtin.import_tasks: "install.yml"
      tags:
        - mpd-install
    - ansible.builtin.import_tasks: "configure.yml"
      tags:
        - mpd-configure
    - ansible.builtin.import_tasks: "validate.yml"
      tags:
        - mpd-validate
  rescue:
    - ansible.builtin.meta: flush_handlers
...
