---
- when:
    - mpd.enable
  tags:
    - mpd
  block:
    - ansible.builtin.import_tasks:
        file: "install.yml"
      tags:
        - mpd-install
    - ansible.builtin.import_tasks:
        file: "configure.yml"
      tags:
        - mpd-configure
    - ansible.builtin.import_tasks:
        file: "{{ playbook_dir + '/includes/audit.yml' }}"
      tags:
        - mpd-audit
  rescue:
    - ansible.builtin.meta: flush_handlers
...
