---
- name: install | clone project repository
  become_user: "{{ user }}"
  ansible.builtin.git:
    repo: "{{ 'https://' + tmux.tpm_repo }}"
    dest: "{{ ansible_facts.user_dir + '/.tmux/plugins/tpm' }}"
    depth: 1

- name: configure | deploy config file
  ansible.builtin.copy:
    src: .tmux.conf
    dest: "{{ ansible_facts.user_dir }}"
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: 0640
...
