---
- when:
    - tmux.enable
  tags:
    - tmux
  block:
    - ansible.builtin.import_tasks:
        file: "install.yml"
      tags:
        - tmux-install
    - ansible.builtin.import_tasks:
        file: "configure.yml"
      tags:
        - tmux-configure
    - ansible.builtin.import_tasks:
        file: "{{ playbook_dir + '/includes/audit.yml' }}"
      tags:
        - tmux-audit
  rescue:
    - ansible.builtin.meta: flush_handlers
...
