---
- name: configure | apply local user configurations
  become_user: "{{ user }}"
  block:
    - name: configure | create necessary directories
      file:
        path: "{{ cava.config.dir }}"
        state: directory

    - name: configure | deploy config file
      copy:
        src: config
        dest: "{{ cava.config.dir }}"
...
