---
- name: install | validate task list parameters
  run_once: true
  assert:
    that:
    quiet: true

- name: install | install package updates
  apt:
    state: latest
    pkg:
      - cava

- name: install | create desktop file
  copy:
    src: cava.desktop
    dest: /usr/share/applications
  notify:
    - update-desktop-database
