---
- name: pre_tasks | set local user
  set_fact:
    user: "{{ ansible_ssh_user }}"
  when:
    - user is undefined

- name: pre_tasks | verify existence of resident user account {{ user }}
  ansible.builtin.getent:
    database: passwd
    key: "{{ user }}"

- name: pre_tasks | gather service facts
  ansible.builtin.service_facts:

- name: pre_tasks | gather package facts
  ansible.builtin.package_facts:
    manager: auto

- name: pre_tasks | gather listening ports facts
  community.general.system.listen_ports_facts:

- name: pre_tasks | get user home directory
  become_user: "{{ user }}"
  ansible.builtin.setup:
    gather_subset: user_dir

- name: pre_tasks | apt upgrade (check mode)
  ansible.builtin.apt:
    update_cache: true
    state: latest
    name: "*"
  changed_when: false
  ignore_errors: "{{ ansible_check_mode }}"
  when:
    - ansible_check_mode

- name: pre_tasks | apt upgrade
  ansible.builtin.apt:
    update_cache: true
    state: latest
    name: "*"
  changed_when: false
  async: 3600
  poll: 0
  register: apt_upgrade
  when:
    - not ansible_check_mode

- name: pre_tasks | wait for apt upgrade
  ansible.builtin.async_status:
    jid: "{{ apt_upgrade.ansible_job_id }}"
  register: job_result
  until: job_result.finished
  retries: 60
  delay: 10
  when:
    - not ansible_check_mode

- name: pre_tasks | install misc pkgs
  ansible.builtin.apt:
    state: latest
    pkg: "{{ misc_pkgs | default([]) }}"

- name: pre_tasks | uninstall unwanted pkgs
  ansible.builtin.apt:
    state: present
    pkg: "{{ misc_pkgs | default([]) }}"

- name: pre_tasks | install goss
  ansible.builtin.get_url:
    url: "https://github.com/aelsabbahy/goss/releases/latest/download/goss-linux-amd64"
    dest: /usr/local/bin/goss
    owner: root
    group: root
    mode: 0755

- name: pre_tasks | create goss tests directory
  ansible.builtin.file:
    path: "{{ goss_dir + '/tests' }}"
    state: directory
    owner: root
    group: root
    mode: 0755

- name: pre_tasks | deploy gossfile
  ansible.builtin.copy:
    content: |
      gossfile:
        tests/*.yml: {}
    dest: "{{ goss_dir + '/goss.yml' }}"
    owner: root
    group: root
    mode: 0644
...
