---
- name: configure | create necessary directories
  ansible.builtin.file:
    dest: "{{ ansible_facts.user_dir + '/' + neofetch.config_dir }}"
    state: directory
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: 0750

- name: configure | deploy config file
  ansible.builtin.copy:
    src: config.conf
    dest: "{{ ansible_facts.user_dir + '/' + neofetch.config_dir }}"
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: 0640

- name: configure | find all scripts
  ansible.builtin.find:
    paths:
      - /etc/update-motd.d
      - /etc/pop-os/update-motd.d
    file_type: file
    depth: 1
    use_regex: true
    excludes:
      - '^00-neofetch-motd$'
  register: motd_scripts

- name: configure | disable default motd scritps
  ansible.builtin.file:
    path: "{{ item.path }}"
    mode: 'ugo-x'
  loop: "{{ motd_scripts.files }}"
  when: motd_scripts.matched > 0

- name: configure | configure motd
  ansible.builtin.copy:
    src: 00-neofetch-motd
    dest: /etc/update-motd.d
    owner: root
    group: root
    mode: 0700
...
