---
- when:
    - neofetch.enable
  tags:
    - neofetch
  block:
    - ansible.builtin.import_tasks: "install.yml"
      tags:
        neofetch-install
    - ansible.builtin.import_tasks: "configure.yml"
      tags:
        neofetch-configure
    - ansible.builtin.import_tasks: "validate.yml"
      tags:
        neofetch-validate
  rescue:
    - ansible.builtin.meta: flush_handlers
...
