---
- when:
    - neofetch.enable
  tags:
    - neofetch
  block:
    - ansible.builtin.import_tasks:
        file: "install.yml"
      tags:
        neofetch-install
    - ansible.builtin.import_tasks:
        file: "configure.yml"
      tags:
        neofetch-configure
    - ansible.builtin.import_tasks:
        file: "{{ playbook_dir + '/includes/audit.yml' }}"
      tags:
        neofetch-audit
  rescue:
    - ansible.builtin.meta: flush_handlers
...
