---
- when:
    - neofetch.enable
  tags:
    - neofetch
  block:
    - ansible.builtin.import_tasks: "install.yml"
      tags:
        neofetch-install
    - ansible.builtin.import_tasks: "configure.yml"
      tags:
        neofetch-configure
    - ansible.builtin.import_tasks: "{{ playbook_dir + '/includes/audit.yml' }}"
      tags:
        neofetch-audit
  rescue:
    - ansible.builtin.meta: flush_handlers
...
