---
- block:
    - import_tasks: "install.yml"
      tags:
        neofetch-install
    - import_tasks: "configure.yml"
      tags:
        neofetch-configure
    - import_tasks: "validate.yml"
      tags:
        neofetch-validate
  rescue:
    - meta: flush_handlers
  tags:
    - neofetch
...
