---
- name: install | install package updates
  ansible.builtin.apt:
    state: present
    pkg:
      - pandoc
      - texlive-xetex
      - texlive-fonts-extra
      - antiword
      - docx2txt
      - poppler-utils
      - man2html
...
