---
- when:
    - pandoc.enable
  tags:
    - pandoc
  block:
    - ansible.builtin.import_tasks: "install.yml"
      tags:
        - pandoc-install
  rescue:
    - ansible.builtin.meta: flush_handlers
...
