---
- name: configure | create local config directory
  ansible.builtin.file:
    dest: "{{ ansible_facts.user_dir + '/' + alacritty.config_dir }}"
    state: directory
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: 0750

- name: configure | deploy config file
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ ansible_facts.user_dir + '/' + alacritty.config_dir }}"
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: 0640
  loop:
    - alacritty.yml
    - nord.yml
...
