---
- name: configure | apply local user configurations
  become_user: "{{ user }}"
  block:
    - name: configure | create local config directory
      file:
        path: "{{ alacritty.config.dir }}"
        state: directory

    - name: configure | deploy config file
      copy:
        src: "{{ item }}"
        dest: "{{ alacritty.config.dir }}"
      loop:
        - alacritty.yml
        - nord.yml
...
