---
- name: install | validate task list parameters
  run_once: true
  assert:
    that:
    quiet: true

- name: install | install package updates
  apt:
    state: latest
    pkg:
      - alacritty

- name: install | install font updates
  apt:
    pkg:
      - fonts-jetbrains-mono
    state: latest
  notify:
    - fc-cache
