---
- name: install | install package updates
  ansible.builtin.apt:
    state: present
    pkg:
      - alacritty

- name: install | install font updates
  ansible.builtin.apt:
    pkg:
      - fonts-jetbrains-mono
    state: present
  notify:
    - fc-cache
...
