---
- when:
    - alacritty.enable
  tags:
    - alacritty
  block:
    - ansible.builtin.import_tasks:
        file: "install.yml"
      tags:
        - alacritty-install
    - ansible.builtin.import_tasks:
        file: "configure.yml"
      tags:
        - alacritty-configure
    - ansible.builtin.import_tasks:
        file: "{{ playbook_dir + '/includes/audit.yml' }}"
      tags:
        - alacritty-audit
  rescue:
    - ansible.builtin.meta: flush_handlers
...
