---
- when:
    - alacritty.enable
  tags:
    - alacritty
  block:
    - ansible.builtin.include_tasks: "install.yml"
      when:
        ansible_distribution == "Pop!_OS"
      tags:
        - alacritty-install
    - ansible.builtin.include_tasks: "build.yml"
      when:
        ansible_distribution == "Kali"
      tags:
        - alacritty-install
    - ansible.builtin.import_tasks: "configure.yml"
      tags:
        - alacritty-configure
    - ansible.builtin.import_tasks: "{{ playbook_dir + '/includes/audit.yml' }}"
      tags:
        - alacritty-audit
  rescue:
    - ansible.builtin.meta: flush_handlers
...
