---
- name: install | validate task list parameters
  run_once: true
  assert:
    that:
    quiet: true

- name: install | install package updates
  apt:
    state: latest
    pkg:
      - pandoc
      - texlive-xetex
      - texlive-fonts-extra
  notify:
    - apt-get clean
