---
- name: Ensure hosts are compatible
  hosts: all
  gather_facts: true
  become: true
  tasks:
    - name: Group by distribution
      ansible.builtin.group_by:
        key: "{{ ansible_distribution }}"
      changed_when: false
  tags:
    - always

- name: Deploy custom configuration
  vars:
    goss_dir: "/opt/goss"
  hosts: "Pop!_OS"
  become: true
  gather_facts: false
  handlers:
    - ansible.builtin.import_tasks: "{{ playbook_dir + '/includes/handlers.yml' }}"
  pre_tasks:
    - ansible.builtin.import_tasks: "{{ playbook_dir + '/includes/pre_tasks.yml' }}"
      tags:
        - always
  roles:
    - alacritty
    - bitwarden_cli
    - bpytop
    - dircolors
    - discord
    - git
    - hardening
    - himalaya
    - mpd
    - ncmpcpp
    - neofetch
    - neovim
    - protonmail_bridge
    - protonvpn_cli
    - qutebrowser
    - ranger
    - signal_desktop
    - zathura
  post_tasks:
    - ansible.builtin.import_tasks: "{{ playbook_dir + '/includes/post_tasks.yml' }}"
      tags:
        - always
...
