---
- name: Ensure hosts are compatible
  hosts: all
  gather_facts: true
  become: true
  tasks:
    - name: Group by distribution
      ansible.builtin.group_by:
        key: "{{ ansible_distribution }}"
      changed_when: false
  tags:
    - always

- name: Deploy custom configuration
  vars_files:
    - includes/vars.yml
  hosts: "Pop!_OS"
  become: true
  gather_facts: false
  handlers:
    - ansible.builtin.import_tasks: "{{ playbook_dir + '/includes/handlers.yml' }}"
  pre_tasks:
    - ansible.builtin.import_tasks: "{{ playbook_dir + '/includes/pre_tasks.yml' }}"
      tags:
        - always
  roles:
    - alacritty
    - bitwarden_cli
    - bpytop
    - git
    - mpd
    - ncmpcpp
    - neofetch
    - neovim
    - protonvpn_cli
    - qemu_kvm
    - qutebrowser
    - ranger
    - remmina
    - signal_desktop
    - tmux
    - zathura
    - zsh
  post_tasks:
    - ansible.builtin.import_tasks: "{{ playbook_dir + '/includes/post_tasks.yml' }}"
      tags:
        - always
...
