---
- name: configure | deploy configuration
  become_user: "{{ user }}"
  block:
    - name: configure | create necessary directories
      file:
        path: "{{ item }}"
        state: directory
      loop:
        - "{{ neovim.config.dir }}"
        - "{{ neovim.vim_plug.dir }}"

    - name: configure | install or update Flake8 Python linter via pip
      pip:
        name: flake8
        state: latest
        extra_args: --user
      when:
        - neovim.vim_plug.enable

    - name: configure | install vim-plug
      uri:
        url: "{{ 'https://' + neovim.vim_plug.url }}"
        dest: "{{ neovim.vim_plug.dest }}"
        creates: "{{ neovim.vim_plug.dest }}"
        return_content: true
        validate_certs: true
      when:
        - neovim.vim_plug.enable

    - name: configure | install plug-in updates
      git:
        repo: "{{ 'https://' + item.value.repo }}"
        dest: "{{ '~/.local/share/nvim/plugged/' + item.value.dest }}"
        force: true
        depth: 1
        single_branch: true
      when:
        - neovim.vim_plug.enable
        - neovim.vim_plug.preinstall_plugins
      loop: "{{ neovim.plugins | dict2items }}"

    - name: configure | deploy init
      copy:
        src: init.lua
        dest: "{{ neovim.config.dir }}"
...
