---
- name: configure | create necessary directories
  ansible.builtin.file:
    path: "{{ ansible_facts.user_dir + '/' + neovim.config_dir }}"
    state: directory
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: 0750

- name: configure | deploy init
  ansible.builtin.copy:
    src: init.lua
    dest: "{{ ansible_facts.user_dir + '/' + neovim.config_dir }}"
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: 0640
...
