---
- name: configure | create necessary directories
  file:
    path: "{{ ansible_facts.user_dir + '/' + item }}"
    state: directory
    owner: "{{ user }}"
    group: "{{ user }}"
  loop:
    - "{{ neovim.config_dir }}"
    - "{{ neovim.vim_plug.dir }}"

- name: configure | install vim-plug
  uri:
    url: "{{ 'https://' + neovim.vim_plug.url }}"
    dest: "{{ ansible_facts.user_dir + '/' + neovim.vim_plug.dest }}"
    creates: "{{ ansible_facts.user_dir + '/' + neovim.vim_plug.dest }}"
    return_content: true
    validate_certs: true
    owner: "{{ user }}"
    group: "{{ user }}"
  when:
    - neovim.vim_plug.enable

- name: configure | install plug-in updates
  become_user: "{{ user }}"
  git:
    repo: "{{ 'https://' + item.value.repo }}"
    dest: "{{ ansible_facts.user_dir + '/.local/share/nvim/plugged/' + item.value.dest }}"
    force: true
    depth: 1
    single_branch: true
  when:
    - neovim.vim_plug.enable
    - neovim.vim_plug.preinstall_plugins
  loop: "{{ neovim.plugins | dict2items }}"

- name: configure | deploy init
  copy:
    src: init.lua
    dest: "{{ ansible_facts.user_dir + '/' + neovim.config_dir }}"
    owner: "{{ user }}"
    group: "{{ user }}"
...
