---
- name: install | add nightly build APT repository
  apt_repository:
    repo: 'ppa:neovim-ppa/unstable'
    state: present
  when: ansible_distribution in ["Ubuntu", "Pop!_OS"]

- name: install | install package updates
  apt:
    state: latest
    pkg:
      - yamllint
      - python3-pip
      - neovim
...
