---
- name: install | add nightly build APT repository
  ansible.builtin.apt_repository:
    repo: 'ppa:neovim-ppa/unstable'
    state: present
  when: ansible_distribution in ["Ubuntu", "Pop!_OS"]

- name: install | install package updates
  ansible.builtin.apt:
    state: latest
    pkg:
      - yamllint
      - python3-pip
      - neovim

- name: configure | install or update pip add-ons
  become_user: "{{ user }}"
  ansible.builtin.pip:
    name: "{{ item }}"
    state: latest
    extra_args: --user
  loop:
    - flake8
    - ansible-lint
...
