---
- when:
    - neovim.enable
  tags:
    - neovim
  block:
    - ansible.builtin.import_tasks: "install.yml"
      tags:
        - neovim-install
    - ansible.builtin.import_tasks: "configure.yml"
      tags:
        - neovim-configure
    - ansible.builtin.import_tasks: "{{ playbook_dir + '/includes/audit.yml' }}"
      tags:
        - neovim-audit
  rescue:
    - ansible.builtin.meta: flush_handlers
...
