---
- block:
    - import_tasks: "install.yml"
      tags:
        - neovim-install
    - import_tasks: "configure.yml"
      tags:
        - neovim-configure
    - import_tasks: "validate.yml"
      tags:
        - neovim-validate
  rescue:
    - meta: flush_handlers
  tags:
    - neovim
...
