name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  push-store-image:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: 'Build the image'
      run: |
        echo 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 | docker login ghcr.io -u chris-m-powell --password-stdin
        docker build . --file Containerfile --tag ghcr.io/chris-m-powell/ansible-controller:latest
        docker push ghcr.io/chris-m-powell/ansible-controller:latest
